
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 03 20:27:59 GMT 2015
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORM = 2;
  public static final int COMA = 7;
  public static final int DOSPUNTOS = 4;
  public static final int EOF = 0;
  public static final int LIST = 3;
  public static final int ID = 10;
  public static final int LC = 6;
  public static final int error = 1;
  public static final int LA = 5;
  public static final int TEXTFIELD = 8;
  public static final int COMBO = 9;
}

